read_log:	read_log.cc
	g++ -Wall -Wno-misleading-indentation -g -O2 -o read_log read_log.cc format.cpp

aprs2igc:	aprs2igc.cc
	g++ -Wall -Wno-misleading-indentation -O2 -o aprs2igc aprs2igc.cc format.cpp

clean:
	rm read_log aprs2igc

